CC      := gcc
CCOPTS  := -ggdb -Wall -D_GNU_SOURCE -Iinclude
CXX     := g++
CXXOPTS := -ggdb -Wall -D_GNU_SOURCE -Dnullptr=NULL -Iinclude -std=gnu++0x
LD      := ld
LDLIBS  := -lm
LDLIBS  := -lpng -lglut -lGLU -lGL -lX11 -lm -lFreeSOLID # `sdl-config --cflags --libs` -lSDL_mixer -lSDL_image
LDFLAGS :=
