CC=gcc
CCOPTS=-Wall -DDEBUG_MAIN
CXX=g++
CXXOPTS=-Wall -DDEBUG_MAIN -std=gnu++0x
LD=ld
LDLIBS=-lm
LDLIBS=-lpng -lglut -lGLU -lGL -lX11 -lm `sdl-config --cflags --libs` -lSDL_mixer -lSDL_image
LDFLAGS=
